[package]
name = "rmon"
description = "Program profiling tool with TUI for unix(like) systems"
version = "0.1.1"
authors = ["wheatfox <enkerewpo@hotmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/enkerewpo/rmon"
keywords = ["cli", "top", "unix"]
edition = "2024"
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
ratatui = "0.29.0"
syscalls = "0.6.18"
sysinfo = "0.33.1"
